// Sample data for the e-commerce site

// Categories
export const categories = [
  {
    id: 1,
    name: "Electronics",
    slug: "electronics",
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 2,
    name: "Clothing",
    slug: "clothing",
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 3,
    name: "Home & Kitchen",
    slug: "home-kitchen",
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 4,
    name: "Beauty",
    slug: "beauty",
    image: "/placeholder.svg?height=400&width=400",
  },
]

// Products
export const products = [
  {
    id: 1,
    title: "Wireless Bluetooth Headphones",
    description:
      "Experience premium sound quality with these comfortable wireless headphones. Features noise cancellation and 20-hour battery life.",
    price: 129.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "Electronics",
    categorySlug: "electronics",
    featured: true,
  },
  {
    id: 2,
    title: "Smart Watch Series 5",
    description:
      "Track your fitness goals, receive notifications, and more with this sleek smartwatch. Water-resistant and long battery life.",
    price: 199.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "Electronics",
    categorySlug: "electronics",
    featured: true,
  },
  {
    id: 3,
    title: "Men's Casual Shirt",
    description: "A comfortable and stylish casual shirt made from 100% cotton. Perfect for any casual occasion.",
    price: 49.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "Clothing",
    categorySlug: "clothing",
    featured: false,
  },
  {
    id: 4,
    title: "Women's Summer Dress",
    description: "A lightweight and flowy summer dress with a beautiful floral pattern. Made from breathable fabric.",
    price: 59.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "Clothing",
    categorySlug: "clothing",
    featured: true,
  },
  {
    id: 5,
    title: "Non-Stick Cookware Set",
    description:
      "A complete set of non-stick cookware including pans, pots, and utensils. Dishwasher safe and easy to clean.",
    price: 89.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "Home & Kitchen",
    categorySlug: "home-kitchen",
    featured: false,
  },
  {
    id: 6,
    title: "Coffee Maker with Grinder",
    description: "Brew fresh coffee with this programmable coffee maker with built-in grinder. Makes up to 12 cups.",
    price: 149.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "Home & Kitchen",
    categorySlug: "home-kitchen",
    featured: true,
  },
  {
    id: 7,
    title: "Skincare Gift Set",
    description: "A complete skincare routine in one set. Includes cleanser, toner, moisturizer, and serum.",
    price: 79.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "Beauty",
    categorySlug: "beauty",
    featured: false,
  },
  {
    id: 8,
    title: "Makeup Brush Set",
    description:
      "Professional quality makeup brushes for flawless application. Set includes 12 brushes with a carrying case.",
    price: 39.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "Beauty",
    categorySlug: "beauty",
    featured: false,
  },
  {
    id: 9,
    title: "Laptop Backpack",
    description:
      "A durable and water-resistant backpack with padded compartment for laptops up to 15 inches. Multiple pockets for organization.",
    price: 69.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "Electronics",
    categorySlug: "electronics",
    featured: false,
  },
  {
    id: 10,
    title: "Wireless Charging Pad",
    description: "Charge your compatible devices wirelessly with this sleek charging pad. Supports fast charging.",
    price: 29.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "Electronics",
    categorySlug: "electronics",
    featured: false,
  },
  {
    id: 11,
    title: "Men's Running Shoes",
    description:
      "Lightweight and comfortable running shoes with excellent support and cushioning. Available in multiple colors.",
    price: 89.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "Clothing",
    categorySlug: "clothing",
    featured: false,
  },
  {
    id: 12,
    title: "Women's Yoga Pants",
    description: "Stretchy and comfortable yoga pants perfect for workouts or casual wear. High-waisted with pocket.",
    price: 44.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "Clothing",
    categorySlug: "clothing",
    featured: false,
  },
  {
    id: 13,
    title: "Blender with To-Go Cup",
    description: "Powerful blender for smoothies and more. Includes a to-go cup for convenience.",
    price: 59.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "Home & Kitchen",
    categorySlug: "home-kitchen",
    featured: false,
  },
  {
    id: 14,
    title: "Bedding Set - Queen",
    description:
      "Soft and comfortable bedding set including duvet cover, fitted sheet, and pillowcases. Made from 100% cotton.",
    price: 99.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "Home & Kitchen",
    categorySlug: "home-kitchen",
    featured: false,
  },
  {
    id: 15,
    title: "Facial Cleansing Brush",
    description: "Electric facial cleansing brush for deep cleaning and exfoliation. Waterproof and rechargeable.",
    price: 49.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "Beauty",
    categorySlug: "beauty",
    featured: false,
  },
  {
    id: 16,
    title: "Perfume Gift Set",
    description: "A collection of luxury perfumes in a beautiful gift box. Perfect for any occasion.",
    price: 119.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "Beauty",
    categorySlug: "beauty",
    featured: false,
  },
]

